name: CI-Packing-all
on:
  push:
    branches: [ main, dev ]
jobs:
  build-win64-new-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: ./.github/actions/setup-python

    - name: Run packing
      run: |
        # cp ./OlivOS/hook.py ./OlivOS/hook_bak.py
        # cp ./OlivOS/hook_pack.py ./OlivOS/hook.py
        uv v
        uv sync --all-extras --dev --all-groups
        uv build
        source .venv/bin/activate
        uv run scripts.py build
      env:
        OLIVOS_ENV_PACK: "1"

    - name: Run artifact
      run: |
        mkdir OlivOS-Win
        cp ./dist/OlivOS.exe ./OlivOS-win/OlivOS.exe
  
    - name: Packing OlivOS-Win
      uses: actions/upload-artifact@v3
      with:
        name: OlivOS-Win-origin
        path: ./OlivOS-Win
    - name: Ready for Packing
      #run: |
      #  mkdir ./OlivOS-Win/lib
      #  curl -L https://github.com/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_windows_amd64.exe -o ./OlivOS-Win/lib/go-cqhttp.exe
      #  curl -L https://github.com/onebot-walle/walle-q/releases/latest/download/walle-q-i686-windows-gnu.exe -o ./OlivOS-Win/lib/walle-q.exe
      run: |
        mkdir ./OlivOS-Win/lib
    - name: Packing OlivOS-Win-with-lib
      uses: actions/upload-artifact@v3
      with:
        name: OlivOS-Win
        path: ./OlivOS-Win

  build-linux-new-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: ./.github/actions/setup-python
      
    - name: Run packing
      run: |
        # cp ./OlivOS/hook.py ./OlivOS/hook_bak.py
        # cp ./OlivOS/hook_pack_debug.py ./OlivOS/hook.py
        uv v
        uv sync --all-extras --dev --all-groups
        uv build
        source .venv/bin/activate
        uv run scripts.py build
      env:
        OLIVOS_ENV_DEBUG: "1"
        OLIVOS_ENV_PACK: "1"

    - name: Run artifact
      run: |
        mkdir OlivOS-PKG
        cp ./dist/OlivOS ./OlivOS-PKG/OlivOS

    - name: Packing OlivOS-PKG
      uses: actions/upload-artifact@v3
      with:
        name: OlivOS-Linux
        path: ./OlivOS-PKG

  build-macos-new-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: ./.github/actions/setup-python

    - name: Run packing
      run: |
        # cp ./OlivOS/hook.py ./OlivOS/hook_bak.py
        # cp ./OlivOS/hook_pack_debug.py ./OlivOS/hook.py
        uv v
        uv sync --all-extras --dev --all-groups
        uv build
        source .venv/bin/activate
        uv run scripts.py build
      env:
        OLIVOS_ENV_DEBUG: "1"
        OLIVOS_ENV_PACK: "1"

    - name: Run artifact
      run: |
        mkdir OlivOS-PKG
        cp ./dist/OlivOS ./OlivOS-PKG/OlivOS

    - name: Packing OlivOS-PKG
      uses: actions/upload-artifact@v3
      with:
        name: OlivOS-MacOS
        path: ./OlivOS-PKG
